Fix missing #include with Boost 1.60 (fixes #33).
Error (with g++) was:

In file included from luabind/luabind/back_reference.hpp:26:0,
                 from luabind/luabind/class.hpp:72,
                 from luabind/src/class.cpp:25:
luabind/luabind/detail/has_get_pointer.hpp:94:22: error: ‘mpl’ in namespace ‘boost’ does not name a type
       typedef boost::mpl::bool_<value> type;
                      ^