Do not try to compile test_out_value (ref #30).
Leads to a compiler error with g++:

In file included from luabind/test/test_out_value.cpp:4:0:
luabind/luabind/out_value_policy.hpp: In instantiation of ‘static int luabind::detail::out_value_converter<Size, Policies>::match(lua_State*, luabind::detail::by_reference<T>, int) [with T = float; int Size = 4; Policies = luabind::detail::null_type; lua_State = lua_State]’:
luabind/luabind/detail/call.hpp:262:9:   required from ‘int luabind::detail::invoke_normal(lua_State*, const luabind::detail::function_object&, luabind::detail::invoke_context&, const F&, Signature, const Policies&, mpl_::long_<1l>, mpl_::true_) [with F = void (*)(float&); Signature = boost::function_types::components<void (*)(float&), boost::add_reference<mpl_::arg<-1> > >; Policies = luabind::detail::policy_cons<luabind::detail::out_value_policy<1, luabind::detail::null_type>, luabind::detail::null_type>; lua_State = lua_State; mpl_::true_ = mpl_::bool_<true>]’
luabind/luabind/detail/call.hpp:94:5:   required from ‘int luabind::detail::invoke0(lua_State*, const luabind::detail::function_object&, luabind::detail::invoke_context&, const F&, Signature, const Policies&, IsVoid, mpl_::false_) [with F = void (*)(float&); Signature = boost::function_types::components<void (*)(float&), boost::add_reference<mpl_::arg<-1> > >; Policies = luabind::detail::policy_cons<luabind::detail::out_value_policy<1, luabind::detail::null_type>, luabind::detail::null_type>; IsVoid = boost::is_void<void>; lua_State = lua_State; mpl_::false_ = mpl_::bool_<false>]’
luabind/luabind/detail/call.hpp:106:4:   required from ‘int luabind::detail::invoke(lua_State*, const luabind::detail::function_object&, luabind::detail::invoke_context&, const F&, Signature, const Policies&) [with F = void (*)(float&); Signature = boost::function_types::components<void (*)(float&), boost::add_reference<mpl_::arg<-1> > >; Policies = luabind::detail::policy_cons<luabind::detail::out_value_policy<1, luabind::detail::null_type>, luabind::detail::null_type>; lua_State = lua_State]’
luabind/luabind/make_function.hpp:63:70:   required from ‘static int luabind::detail::function_object_impl<F, Signature, Policies>::entry_point(lua_State*) [with F = void (*)(float&); Signature = boost::function_types::components<void (*)(float&), boost::add_reference<mpl_::arg<-1> > >; Policies = luabind::detail::policy_cons<luabind::detail::out_value_policy<1, luabind::detail::null_type>, luabind::detail::null_type>; lua_State = lua_State]’
luabind/luabind/make_function.hpp:32:27:   required from ‘luabind::detail::function_object_impl<F, Signature, Policies>::function_object_impl(F, const Policies&) [with F = void (*)(float&); Signature = boost::function_types::components<void (*)(float&), boost::add_reference<mpl_::arg<-1> > >; Policies = luabind::detail::policy_cons<luabind::detail::out_value_policy<1, luabind::detail::null_type>, luabind::detail::null_type>]’
luabind/luabind/make_function.hpp:107:5:   required from ‘luabind::adl::object luabind::make_function(lua_State*, F, Signature, Policies) [with F = void (*)(float&); Signature = boost::function_types::components<void (*)(float&), boost::add_reference<mpl_::arg<-1> > >; Policies = luabind::detail::policy_cons<luabind::detail::out_value_policy<1, luabind::detail::null_type>, luabind::detail::null_type>; lua_State = lua_State]’
luabind/luabind/function.hpp:28:72:   required from ‘void luabind::detail::function_registration<F, Policies>::register_(lua_State*) const [with F = void (*)(float&); Policies = luabind::detail::policy_cons<luabind::detail::out_value_policy<1, luabind::detail::null_type>, luabind::detail::null_type>; lua_State = lua_State]’
luabind/test/test_out_value.cpp:22:1:   required from here
luabind/luabind/out_value_policy.hpp:126:71: error: cannot call member function ‘int luabind::native_converter_base<T, Derived>::match(lua_State*, luabind::detail::by_value<T>, int) [with T = float; Derived = luabind::default_converter<float, void>; lua_State = lua_State]’ without object
             return converter::match(L, LUABIND_DECORATE_TYPE(T), index);
                                                                       ^