Fix unused variable warnings for self and const_self with GCC.
This warnings may be suppressed by declaring variables as const.

./luabind/operator.hpp:347: warning: ‘luabind::<unnamed>::self’ defined but not used

The explicit initialisation with default constructor is needed for GCC 4.4.

./luabind/operator.hpp:347: error: uninitialized const ‘luabind::<unnamed>::self’
./luabind/operator.hpp:348: error: uninitialized const ‘luabind::<unnamed>::const_self’